config/routes.rb
Podcast::Application.routes.draw do

  get "sessions/new"
  get "sessions/create"
  get "admins/new"
  get "admins/create"
  root to: 'landing#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :admins, only: [:new, :create]
  resources :episodes do
    resources :suggeestions, only:[:new,:create]
  end
  
end

app/models/add_attachment_to_episodes.rb
class AddAttachmentToEpisodes < ActiveRecord::Base

end

app/models/add_type_to_episodes.rb
class AddTypeToEpisodes < ActiveRecord::Base

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
  validates :email, uniqueness: true

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  
  has_many :suggestions
  has_attached_file :track
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  validates :title,:description,:release_date,:type, presence: true

  validates :runtime_in_minutes,
    numericality: { only_integer: true }

  validate :release_date_is_in_the_future

  protected

  def release_date_is_in_the_future
    if release_date.present?
      errors.add(:release_date, "should probably be in the future") if release_date < Date.today
    end
  end

end

app/models/landing.rb
class LandingPage < ActiveRecord::Base
  
  
end

app/models/suggestions.rb
class Suggestions < ActiveRecord::Base
  belongs_to :episode

  validates :episode, :text, presence: true

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  
  namespace :adim do
    resources :episodes   
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)

    if @admin.save
      session[:admin_id] = @admin.id # auto log in
      redirect_to episodes_path, notice:"Welcome aboard!"
    else
      render :new
    end
  end

  protected

  def admin_params
    params.require(:admin).permit(:email,:password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  protected

  def current_admin
    @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end

  helper_method :current_admin

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  
  def index
    type = params[:type]
    if type == 'vita'
      @episodes = Episode.where(type: 'vita')
    else
      @episodes = Episode.where(type: 'SFNAPCPS')
    end        
  end

  def show
    @episodes = Episode.find(params[:id])
  end

  def new
    @episodes = Episode.new
  end

  def edit
    @episodes = Episode.find(params[:id])
  end

  def create
    @admin = Admin.new(admin_params)
    @episodes = Episode.new(episode_params)

      if @episode.save
        redirect_to episode_path, notice:"#{episode.title} was submitted successfully!"
      else
        render :new
      end
  end

  def update
    @episode = Episode.find(params[:id])

      if @episode.update_attributes(episode_params)
        redirect_to episode_path(@episode)
      else
        render :edit
      end
  end

  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy
    redirect_to episode_path
  end

  protected
  #need to add file column name
  def episode_params
    params.require(:episode).permit(:title, :description, :runtime_in_minutes, :poster_image_url, :release_date, :type)
  end

  def admin_params
    params.require(:admin).permit(:avatar)
  end


end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

    def index
      render :index
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    admin = Admin.find_by(email: params[:email])

    if admin && admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      redirect_to movies_pathnotice: "Welcome back!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/suggestion_controller.rb
class SuggestionsController < ApplicationController

  def new
    @episode_id = Episode_id.find(params[:episode_id_id])
    @suggestion = @episode_id.suggestions.build
  end

  def create
    @episode_id = Episode_id.find(params[:episode_id_id])
    @suggestion = @episode_id.suggestions.build(suggestion_params)
    @suggestion.admin_id = current_admin.id

    if @suggestion.save
      redirect_to @episode_id, notice: "Suggestion created successfully :)"
    else
      render :new
    end
  end

  protected

  def suggestion_params
    params.require(:suggestion).permit(:text)
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admins/create.html.erb
<h1>Admins#create</h1>
<p>Find me in app/views/admins/create.html.erb</p>

app/views/admins/new.html.erb
<h1>Sign Up</h1>
<%= form_for @admin do |f| %>
  <% if @admin.errors.any? %>
    <div>
      <%= pluralize(@admin.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @admin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/episodes/_form.htm.erb
<%= link_to "Home", episode_path(@episode) %>

<h2>Upload episode.</h2>
<%= form_for @episode do |f| %>
<% if @episode.errors.any? %>
    <div>
      <%= pluralize(@episode.errors.count, "error") %> prevented this episode from being submitted:
      <ul>
        <% @episode.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label "release_date" %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
    <%= f.label "runtime_in_minutes" %><br>
    <%= f.number_field "runtime_in_minutes" %>
  </div>
  <div>
    <%= f.label "Thumbnail Upload" %><br>
  </div>
  <div>
    <%= f.label "description" %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/episodes/edit.html.erb
<%= render 'form' %>

app/views/episodes/index.html.erb
<h1> SFNAPCPS! </h1>
<% @episodes.each do |episode| %>
  <%= link_to image_tag(episode.poster_image_url), episode_path(episode) %>
  <h2><%= link_to episode.title, episode_path(episode) %></h2>
  <p><%= episode.description %></p>
  <h4> <%= link_to release_date %> | <%= episode.runtime_in_minutes %> minutes</h4>
  <hr>
<% end %>

app/views/episodes/new.html.erb
<%= render 'form' %>

app/views/episodes/show.html.erb
<%= link_to "Home", episodes_path %><br/>


<%= link_to image_tag(<%= image_tag @admin.avatar.url(:thumb) %>), episode_path(@episode) %>
<h2><%= @episode.title %> (<%= link_to "edit", edit_episode_path(@episode) %>, <%= link_to "delete", episode_path(@episode), method: :delete, confirm: "Are You sure???" %>)</h2>
<h4> <%= @episode.release_date %> | <%= @episode.runtime_in_minutes %> minutes</h4>
<p><%= @episode.description %></p>

<div id="sm2-container">
  <script src="/soundmanager2/script/soundmanager2.js"></script>
  <script>
  soundManager.setup({
    url: '/soundmanager2/swf/soundmanager2.swf',
    flashVersion: 9, 
    preferFlash: false,
    onready: function() {
      var mySound = soundManager.createSound({
        id: 'episode',
        url: '/path/to/an.mp3'
      });
      mySound.play();
       stream: true,
       volume: 100, 
       multiShot: true 
    },
    ontimeout: function() {
      console.log("Hrmm, the player could not start")
    }
  });
  </script>
</div>  

app/views/landing/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Landing Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link href='http://fonts.googleapis.com/css?family=Butcherman' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div class="container">
      <section>
       <%= link_to 'VITA', episodes_path(:type=>'vita'),class: "vita btn btn-lg active col-md-2 col-md-offset-6"  %> 
       <%= link_to 'SFNAPCPS', episodes_path,class: "vita btn btn-lg active col-md-2 col-md-offset-6"  %>
       <!--  <button id="leftpaw" type="button" class="btn btn-lg active col-md-2 col-md-offset-0" href="#clear">SFNAPCPS</button> -->
      </section>
   </div>
  </body>
</html>

// <script type="text/javascript">
  
// $('#leftpaw').click(function(){
//   console.log('hello');
// })

// </script>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_admin %>
      Signed in as <%= current_admin.email %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_admin_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Podcast</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body> 
  <% flash.each do |key, value| %>
   <%= content_tag(:div, value) %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>